/**
 * XML output style generator.
 */

import type { OutputContext } from "../generator.js";

export function generateXml(context: OutputContext): string {
	const parts: string[] = [];

	// Header comment
	parts.push("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
	parts.push(`<!-- Generated by Pi Repomix on ${context.generationDate} -->`);
	parts.push(`<!-- Repository: ${context.processedFiles.length} files, ${context.totalTokens} tokens, ${context.totalLines} lines -->`);
	parts.push("");

	// File summary
	if (context.fileSummary) {
		parts.push("<file_summary>");
		parts.push("  <purpose>This file contains a packed representation of the entire repository's contents.</purpose>");
		parts.push("  <format>");
		parts.push("    Each file is wrapped in a <file> element with a 'path' attribute.");
		parts.push("    File contents are contained within the element body.");
		parts.push("  </format>");
		parts.push("  <usage_guidelines>");
		parts.push("    - Treat this file as read-only");
		parts.push("    - Use the 'path' attribute to identify files");
		parts.push("    - Binary files are marked with [BINARY FILE] placeholder");
		parts.push("  </usage_guidelines>");
		parts.push("</file_summary>");
		parts.push("");
	}

	// User-provided header
	if (context.headerText) {
		parts.push("<user_provided_header>");
		parts.push(escapeXml(context.headerText));
		parts.push("</user_provided_header>");
		parts.push("");
	}

	// Repository stats
	parts.push("<repository>");
	parts.push("  <stats>");
	parts.push(`    <file_count>${context.totalFiles}</file_count>`);
	parts.push(`    <total_lines>${context.totalLines}</total_lines>`);
	parts.push(`    <total_tokens>${context.totalTokens}</total_tokens>`);
	parts.push("  </stats>");

	// Top files
	if (context.topFiles.length > 0) {
		parts.push("  <top_files>");
		for (const file of context.topFiles) {
			parts.push(`    <file path="${escapeXml(file.path)}" tokens="${file.tokens}" lines="${file.lines}" />`);
		}
		parts.push("  </top_files>");
	}
	parts.push("");

	// Directory structure
	if (context.directoryStructure && context.directoryTree) {
		parts.push("  <directory_structure>");
		parts.push(escapeXml(context.directoryTree));
		parts.push("  </directory_structure>");
		parts.push("");
	}

	// Files
	if (context.filesEnabled) {
		parts.push("  <files>");
		for (const file of context.processedFiles) {
			parts.push(`    <file path="${escapeXml(file.path)}" language="${escapeXml(file.language)}" tokens="${file.tokens}" lines="${file.lines}">`);
			parts.push(escapeXml(file.content));
			parts.push("    </file>");
		}
		parts.push("  </files>");
		parts.push("");
	}

	// Git diffs
	if (context.gitDiff) {
		parts.push("  <git_diffs>");
		parts.push("    <git_diff_work_tree>");
		parts.push(escapeXml(context.gitDiff));
		parts.push("    </git_diff_work_tree>");
		if (context.gitDiffStaged) {
			parts.push("    <git_diff_staged>");
			parts.push(escapeXml(context.gitDiffStaged));
			parts.push("    </git_diff_staged>");
		}
		parts.push("  </git_diffs>");
		parts.push("");
	}

	// Git logs
	if (context.gitLogs && context.gitLogs.length > 0) {
		parts.push("  <git_logs>");
		for (const commit of context.gitLogs) {
			parts.push("    <git_log_commit>");
			parts.push(`      <date>${escapeXml(commit.date)}</date>`);
			parts.push(`      <message>${escapeXml(commit.message)}</message>`);
			parts.push("      <files>");
			for (const file of commit.files) {
				parts.push(`        <file>${escapeXml(file)}</file>`);
			}
			parts.push("      </files>");
			parts.push("    </git_log_commit>");
		}
		parts.push("  </git_logs>");
		parts.push("");
	}

	parts.push("</repository>");

	// Instruction
	if (context.instruction) {
		parts.push("");
		parts.push("<instruction>");
		parts.push(escapeXml(context.instruction));
		parts.push("</instruction>");
	}

	return parts.join("\n");
}

function escapeXml(str: string): string {
	return str
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;")
		.replace(/"/g, "&quot;")
		.replace(/'/g, "&apos;");
}
